version: '3.8'
services:

  #PHP Service
  php:
    build:
      context: ./src/project
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: project
      SERVICE_TAGS: dev
      COMPOSER_MEMORY_LIMIT: -1
    working_dir: /var/www
    volumes:
      - ./src/project:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      - development

  #Node Service
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    container_name: node
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./src/project:/var/www
    networks:
      - development

  #Nginx Service
  nginx:
    image: library/nginx:1.19.3-alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src/project:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - development
    depends_on:
      - php

  #MySQL Service
  mysql:
    image: library/mysql:8
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: development
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - development

#Docker Networks
networks:
  development:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
